"Autogenerated .vimrc entries
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

set rtp+=~/.fzf
Plugin 'VundleVim/Vundle.vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'PProvost/vim-ps1'
Plugin 'itchyny/lightline.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'junegunn/fzf.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'elmcast/elm-vim'

call vundle#end()            

map <F5> :!clear & mix test<CR>
map <F6> :!clear & elixir %<CR>
inoremap jj <ESC>

filetype plugin indent on    
syntax on
set laststatus=2
set statusline+=%#warningmsg#
set statusline+=%*

set expandtab
set shiftwidth=2
set softtabstop=2
set autowrite
set incsearch
set nocompatible
set number
set ttyfast
set hlsearch 
set laststatus=2
set noshowmode

set t_Co=256
syntax enable
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized

let g:lightline = { 'colorscheme': 'solarized'}
let g:lightline = {
      \   'component_function': {
      \     'filename': 'LightLineFilename'
      \   },
      \   'colorscheme': 'solarized'
      \ }
function! LightLineFilename()
  return expand('%')
endfunction

filetype plugin on
set omnifunc=syntaxcomplete#Complete
set wildignore+=*/node_modules/*,*/deps/*,*/tmp/*,*.so,*.swp,*.zip
noremap <C-p> :Files<cr>

let $FZF_DEFAULT_COMMAND = 'ack -g ""'

autocmd BufWritePre * %s/\s\+$//e
