grep '"Autogenerated .vimrc entries' ~/.vimrc >/dev/null

if [ $? -ne 0 ]; then
  echo "Backing up .vimrc"
  mv ~/.vimrc ~/.vimrc.old

  echo 'Installing Vundle - https://github.com/VundleVim/Vundle.vim'
  git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim

  echo 'Installing Vim plugins'
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  echo 'set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
' > "${script_dir}"/vimrctemp
  grep "Plugin '" .vimrc >> "${script_dir}"/vimrctemp
  echo 'call vundle#end()            
' >> "${script_dir}"/vimrctemp

  ln -s "${script_dir}"/vimrctemp ~/.vimrc
  vim +PluginInstall +qall

  rm ~/.vimrc
  rm "${script_dir}"/vimrctemp

  echo 'Setting up .vimrc'
  ln -s "${script_dir}"/.vimrc ~/.vimrc
else
  echo '.vimrc already appears to be set up.'
fi
